# CNN
    # Seed None
        # Negative with test set CNN
        python analyze_linear_classification_new.py --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        python analyze_linear_classification_new.py --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        # Negative no test set CNN
        python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar

    # Seed 1
        # Negative with test set CNN
        CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        # Negative no test set CNN
        CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar

    # Seed 10
        # Negative with test set CNN
        python analyze_linear_classification_new.py --seed 10 --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        python analyze_linear_classification_new.py --seed 10 --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        # Negative no test set CNN
        python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar

    # Seed 100
        # Negative with test set CNN
        python analyze_linear_classification_new.py --seed 100 --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        python analyze_linear_classification_new.py --seed 100 --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        # Negative no test set CNN
        python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar

    # Seed 1000
        # Negative with test set CNN
        python analyze_linear_classification_new.py --seed 1000 --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        python analyze_linear_classification_new.py --seed 1000 --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        # Negative no test set CNN
        python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode cnn_scratch --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
        python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode cnn_moco_yfcc_feb18_gpu_8_bucket_0 --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar

    # later
    python analyze_linear_classification_new.py --use_negative_samples --train_mode cnn_imgnet --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
    python analyze_linear_classification_new.py --use_negative_samples --train_mode cnn_byol --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
    python analyze_linear_classification_new.py --use_negative_samples --train_mode cnn_moco --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
    python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode cnn_imgnet --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
    python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode cnn_byol --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
    python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode cnn_moco --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar


# Seed None
# Negative no test set
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
# Negative with test set
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode raw_feature --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
python analyze_linear_classification_new.py --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar


# Seed 1
# Negative no test set
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
# Negative with test set
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode raw_feature --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1 --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar


# Seed 10
# Negative no test set
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
# Negative with test set
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode raw_feature --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 10 --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar


# Seed 100
# Negative no test set
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
# Negative with test set
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode raw_feature --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 100 --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar


# Seed 1000
# Negative no test set
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode no_test_set --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
# Negative with test set
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode moco_v2_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode byol_imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode imgnet_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_mlp --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode raw_feature --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode moco_v2_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode byol_imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode imgnet_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar
CUDA_VISIBLE_DEVICES=1 python analyze_linear_classification_new.py --seed 1000 --mode default --use_negative_samples --train_mode moco_v2_yfcc_feb18_bucket_0_gpu_8_linear --folder_path /scratch/zhiqiu/yfcc100m_all/images_minbyte_10_valid_uploaded_date_feb_18/ --num_of_bucket 11 --moco_model /project_data/ramanan/zhiqiu/yfcc_moco_models/feb_18_bucket_11_idx_0_gpu_8/checkpoint_0199.pth.tar








